apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
<<<<<<< HEAD
  replicas: 4
=======
  replicas: 10
>>>>>>> parent of 780623a... Update guestbook-ui-deployment.yaml
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
